/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"
)


// InofficialApiRouter defines the required methods for binding the api requests to a responses for the InofficialApi
// The InofficialApiRouter implementation should parse necessary information from the http request, 
// pass the data to a InofficialApiServicer to perform the required actions, then write the service results to the http response.
type InofficialApiRouter interface { 
	BridgeConfigGet(http.ResponseWriter, *http.Request)
	BridgeConfigPut(http.ResponseWriter, *http.Request)
	LocksGet(http.ResponseWriter, *http.Request)
	LocksIdConfigGet(http.ResponseWriter, *http.Request)
	LocksIdCurrentStateGet(http.ResponseWriter, *http.Request)
	LocksIdDelete(http.ResponseWriter, *http.Request)
	LocksIdGet(http.ResponseWriter, *http.Request)
	LocksIdHistoryGet(http.ResponseWriter, *http.Request)
	LocksIdLastStateGet(http.ResponseWriter, *http.Request)
	LocksIdPut(http.ResponseWriter, *http.Request)
}
// OfficialApiRouter defines the required methods for binding the api requests to a responses for the OfficialApi
// The OfficialApiRouter implementation should parse necessary information from the http request, 
// pass the data to a OfficialApiServicer to perform the required actions, then write the service results to the http response.
type OfficialApiRouter interface { 
	CallbackAddGet(http.ResponseWriter, *http.Request)
	CallbackListGet(http.ResponseWriter, *http.Request)
	CallbackRemoveGet(http.ResponseWriter, *http.Request)
	ListGet(http.ResponseWriter, *http.Request)
	LockActionGet(http.ResponseWriter, *http.Request)
	LockStateGet(http.ResponseWriter, *http.Request)
}


// InofficialApiServicer defines the api actions for the InofficialApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type InofficialApiServicer interface { 
	BridgeConfigGet() (interface{}, error)
	BridgeConfigPut(BridgeConfig) (interface{}, error)
	LocksGet() (interface{}, error)
	LocksIdConfigGet(string) (interface{}, error)
	LocksIdCurrentStateGet(string) (interface{}, error)
	LocksIdDelete(string) (interface{}, error)
	LocksIdGet(string) (interface{}, error)
	LocksIdHistoryGet(string, string, string) (interface{}, error)
	LocksIdLastStateGet(string) (interface{}, error)
	LocksIdPut(string, Lock) (interface{}, error)
}


// OfficialApiServicer defines the api actions for the OfficialApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type OfficialApiServicer interface { 
	CallbackAddGet(string) (interface{}, error)
	CallbackListGet() (interface{}, error)
	CallbackRemoveGet(string) (interface{}, error)
	ListGet() (interface{}, error)
	LockActionGet(string, string, string) (interface{}, error)
	LockStateGet(string) (interface{}, error)
}
