/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"errors"
)

// InofficialApiService is a service that implents the logic for the InofficialApiServicer
// This service should implement the business logic for every endpoint for the InofficialApi API. 
// Include any external packages or services that will be required by this service.
type InofficialApiService struct {
}

// NewInofficialApiService creates a default api service
func NewInofficialApiService() InofficialApiServicer {
	return &InofficialApiService{}
}

// BridgeConfigGet - Read the current bridge configuration
func (s *InofficialApiService) BridgeConfigGet() (interface{}, error) {
	// TODO - update BridgeConfigGet with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'BridgeConfigGet' not implemented")
}

// BridgeConfigPut - Update the current bridge configuration
func (s *InofficialApiService) BridgeConfigPut(bridgeConfig BridgeConfig) (interface{}, error) {
	// TODO - update BridgeConfigPut with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'BridgeConfigPut' not implemented")
}

// LocksGet - Returns a list of linked locks
func (s *InofficialApiService) LocksGet() (interface{}, error) {
	// TODO - update LocksGet with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksGet' not implemented")
}

// LocksIdConfigGet - Returns the configuration of the lock
func (s *InofficialApiService) LocksIdConfigGet(id string) (interface{}, error) {
	// TODO - update LocksIdConfigGet with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksIdConfigGet' not implemented")
}

// LocksIdCurrentStateGet - Returns the current state of the keyturner
func (s *InofficialApiService) LocksIdCurrentStateGet(id string) (interface{}, error) {
	// TODO - update LocksIdCurrentStateGet with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksIdCurrentStateGet' not implemented")
}

// LocksIdDelete - Update a linked lock
func (s *InofficialApiService) LocksIdDelete(id string) (interface{}, error) {
	// TODO - update LocksIdDelete with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksIdDelete' not implemented")
}

// LocksIdGet - Returns a linked lock
func (s *InofficialApiService) LocksIdGet(id string) (interface{}, error) {
	// TODO - update LocksIdGet with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksIdGet' not implemented")
}

// LocksIdHistoryGet - Returns the history of log action
func (s *InofficialApiService) LocksIdHistoryGet(id string, offset string, count string) (interface{}, error) {
	// TODO - update LocksIdHistoryGet with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksIdHistoryGet' not implemented")
}

// LocksIdLastStateGet - Returns the last state of the keyturner without creating a connection
func (s *InofficialApiService) LocksIdLastStateGet(id string) (interface{}, error) {
	// TODO - update LocksIdLastStateGet with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksIdLastStateGet' not implemented")
}

// LocksIdPut - Update a linked lock
func (s *InofficialApiService) LocksIdPut(id string, lock Lock) (interface{}, error) {
	// TODO - update LocksIdPut with the required logic for this service method.
	// Add api_inofficial_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'LocksIdPut' not implemented")
}
