/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"
)

// EventsApiService is a service that implents the logic for the EventsApiServicer
// This service should implement the business logic for every endpoint for the EventsApi API.
// Include any external packages or services that will be required by this service.
type EventsApiService struct {
}

// NewEventsApiService creates a default api service
func NewEventsApiService() EventsApiServicer {
	return &EventsApiService{}
}

// EventsGet - Receive server-sent events from bridge
func (s *EventsApiService) EventsGet(w http.ResponseWriter, r *http.Request) {
	// TODO - update EventsGet with the required logic for this service method.
	// Add api_events_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return
}
