/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"strings"

	log "github.com/sirupsen/logrus"

	"net/http"
	"time"
)

func Logger(inner http.Handler, name string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		inner.ServeHTTP(w, r)
		uri := r.RequestURI
		tokens, ok := r.URL.Query()["token"]
		if ok {
			for _, token := range tokens {
				uri = strings.ReplaceAll(uri, token, "***")
			}
		}

		log.WithField("method", r.Method).WithField("uri", uri).WithField("rtt", time.Since(start)).Infoln("API request")
	})
}
