/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Callback struct {

	Id int32 `json:"id,omitempty"`

	Url string `json:"url,omitempty"`
}
