/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type LockAction struct {

	Success bool `json:"success,omitempty"`

	BatteryCritical bool `json:"batteryCritical,omitempty"`
}
