/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type InlineResponse200 struct {

	Event string `json:"event,omitempty"`

	Data map[string]interface{} `json:"data,omitempty"`
}
