/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type InfoIds struct {

	HardwareId string `json:"hardwareId,omitempty"`

	ServerId string `json:"serverId,omitempty"`
}
