/*
 * Keyturner api
 *
 * Keyturner api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type InfoVersions struct {

	FirmwareVersion string `json:"firmwareVersion,omitempty"`

	WifiFirmwareVersion string `json:"wifiFirmwareVersion,omitempty"`
}
