// Code generated by "stringer -type CompletionStatus -trimprefix CompletionStatus"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompletionStatusSuccess-0]
	_ = x[CompletionStatusMotorBlocked-1]
	_ = x[CompletionStatusCanceled-2]
	_ = x[CompletionStatusTooRecent-3]
	_ = x[CompletionStatusBusy-4]
	_ = x[CompletionStatusLowMotorVoltage-5]
	_ = x[CompletionStatusClutchFailure-6]
	_ = x[CompletionStatusMotorPowerFailure-7]
	_ = x[CompletionStatusIncompleteFailure-8]
	_ = x[CompletionStatusOtherError-254]
	_ = x[CompletionStatusUnknown-255]
}

const (
	_CompletionStatus_name_0 = "SuccessMotorBlockedCanceledTooRecentBusyLowMotorVoltageClutchFailureMotorPowerFailureIncompleteFailure"
	_CompletionStatus_name_1 = "OtherErrorUnknown"
)

var (
	_CompletionStatus_index_0 = [...]uint8{0, 7, 19, 27, 36, 40, 55, 68, 85, 102}
	_CompletionStatus_index_1 = [...]uint8{0, 10, 17}
)

func (i CompletionStatus) String() string {
	switch {
	case i <= 8:
		return _CompletionStatus_name_0[_CompletionStatus_index_0[i]:_CompletionStatus_index_0[i+1]]
	case 254 <= i && i <= 255:
		i -= 254
		return _CompletionStatus_name_1[_CompletionStatus_index_1[i]:_CompletionStatus_index_1[i+1]]
	default:
		return "CompletionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
