// Code generated by "stringer -type DoorSensorState -trimprefix DoorSensorState"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DoorSensorStateUnavailable-0]
	_ = x[DoorSensorStateDeactivated-1]
	_ = x[DoorSensorStateDoorClosed-2]
	_ = x[DoorSensorStateDoorOpened-3]
	_ = x[DoorSensorStateDoorStateUnknown-4]
	_ = x[DoorSensorStateCalibrating-5]
}

const _DoorSensorState_name = "UnavailableDeactivatedDoorClosedDoorOpenedDoorStateUnknownCalibrating"

var _DoorSensorState_index = [...]uint8{0, 11, 22, 32, 42, 58, 69}

func (i DoorSensorState) String() string {
	if i >= DoorSensorState(len(_DoorSensorState_index)-1) {
		return "DoorSensorState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DoorSensorState_name[_DoorSensorState_index[i]:_DoorSensorState_index[i+1]]
}
