// Code generated by "stringer -type LockAction -trimprefix LockAction"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LockActionUnlock-1]
	_ = x[LockActionLock-2]
	_ = x[LockActionUnlatch-3]
	_ = x[LockActionLocknGo-4]
	_ = x[LockActionLocknGoUnlatch-5]
	_ = x[LockActionFullLock-6]
	_ = x[LockActionFobAction1-129]
	_ = x[LockActionFobAction2-130]
	_ = x[LockActionFobAction3-131]
}

const (
	_LockAction_name_0 = "UnlockLockUnlatchLocknGoLocknGoUnlatchFullLock"
	_LockAction_name_1 = "FobAction1FobAction2FobAction3"
)

var (
	_LockAction_index_0 = [...]uint8{0, 6, 10, 17, 24, 38, 46}
	_LockAction_index_1 = [...]uint8{0, 10, 20, 30}
)

func (i LockAction) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _LockAction_name_0[_LockAction_index_0[i]:_LockAction_index_0[i+1]]
	case 129 <= i && i <= 131:
		i -= 129
		return _LockAction_name_1[_LockAction_index_1[i]:_LockAction_index_1[i+1]]
	default:
		return "LockAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
