// Code generated by "stringer -type NukiState -trimprefix NukiState"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NukiStateUninitalized-0]
	_ = x[NukiStatePairingMode-1]
	_ = x[NukiStateDoorMode-2]
	_ = x[NukiStateMaintenanceMode-4]
}

const (
	_NukiState_name_0 = "UninitalizedPairingModeDoorMode"
	_NukiState_name_1 = "MaintenanceMode"
)

var (
	_NukiState_index_0 = [...]uint8{0, 12, 23, 31}
)

func (i NukiState) String() string {
	switch {
	case i <= 2:
		return _NukiState_name_0[_NukiState_index_0[i]:_NukiState_index_0[i+1]]
	case i == 4:
		return _NukiState_name_1
	default:
		return "NukiState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
