// Code generated by "stringer -type Trigger -trimprefix Trigger"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TriggerSystem-0]
	_ = x[TriggerManual-1]
	_ = x[TriggerButton-2]
	_ = x[TriggerAutomatic-3]
	_ = x[TriggerAutoLock-6]
}

const (
	_Trigger_name_0 = "SystemManualButtonAutomatic"
	_Trigger_name_1 = "AutoLock"
)

var (
	_Trigger_index_0 = [...]uint8{0, 6, 12, 18, 27}
)

func (i Trigger) String() string {
	switch {
	case i <= 3:
		return _Trigger_name_0[_Trigger_index_0[i]:_Trigger_index_0[i+1]]
	case i == 6:
		return _Trigger_name_1
	default:
		return "Trigger(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
